bankproject/bankproject/bankapp/urls.py
from . import views
from django.urls import path,include
app_name = 'bankapp'
urlpatterns = [

    path('',views.index,name='index'),
    # path('login',views.login,name='login'),
    # path('registrations',views.register,name='register'),
    # path('apply',views.apply,name='apply'),
]

bankproject/bankproject/bankproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bankapp.urls')),
    path('credentials/', include('credentials.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

bankproject/bankproject/credentials/urls.py
from . import views
from django.urls import path
app_name = 'credentials'
urlpatterns = [
    path('registrations',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('home', views.home, name='home'),
    path('apply',views.apply,name='apply'),
    path('submit',views.submit,name='submit'),
]

bankproject/bankproject/bankapp/models.py
from django.db import models

# Create your models here.

bankproject/bankproject/credentials/models.py
from django.db import models

# Create your models here.

bankproject/bankproject/bankapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"index.html")
# def login(request):
#     return render(request,"login.html")
#
# def register(request):
#     return render(request,"register.html")

# def apply(request):
#     return render(request,"apply.html")

bankproject/bankproject/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from django.shortcuts import render

# Create your views here.
def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('credentials:home')
        else:
            messages.info(request,"invalid credentials")
            return redirect('credentials:login')
    return render(request,'login.html')
def register(request):
    if request.method == 'POST':
        user_name = request.POST['user_name']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password == cpassword:
            if User.objects.filter(username = user_name).exists():
                messages.info(request,"username taken")
                return redirect('credentials:register')
            else:
                user = User.objects.create_user(username=user_name,password=password)
                user.save()
                print("User created")
                return redirect('credentials:login')
        else:
            messages.info(request,"password not matched")
            return redirect('credentials:register')
        return redirect('login.html')
    return render(request,"register.html")


def logout(request):
    auth.logout(request)
    return redirect('/')
def home(request):
    return render(request,"home.html")
def submit(request,):
    if request.method == 'POST':
        messages.success(request, "successfully applied")
        return redirect('credentials:apply')
def apply(request):
    return render(request,"apply.html")

bankproject/bankproject/templates/apply.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Application form</title>
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<section class="site-section bg-light" id="contact-section" data-aos="fade">
      <div class="container">
     <div class="row">
          <div class="col-md-12 mb-5">



            <form action="submit" class="p-5 bg-white" method="post">
                	{% csrf_token %}

              <h2 class="h4 text-black mb-5">Application Form</h2>

              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="fname" >First Name</label>
                  <input type="text" id="fname" class="form-control" required>
                </div>
                <div class="col-md-6">
                  <label class="text-black" for="lname">Last Name</label>
                  <input type="text" id="lname" class="form-control" required>
                </div>
              </div>
            <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="fname">Date of birth</label>
                  <input type="date" id="dob" class="form-control" required>
                </div>
                <div class="col-md-6">
                  <label class="text-black" for="lname">Gender</label>

                       <select id="gender" class="form-control" required>

                           <option >Male</option>
                           <option >Female</option>
                       </select>

                </div>
              </div>
                <div class="row form-group">

                <div class="col-md-12">
                  <label class="text-black" for="email">Phone Number</label>
                  <input type="number" id="phonenumber" class="form-control" required>
                </div>
              </div>
              <div class="row form-group">

                <div class="col-md-12">
                  <label class="text-black" for="email">Email</label>
                  <input type="email" id="email" class="form-control" required>
                </div>
              </div>



              <div class="row form-group">
                <div class="col-md-12">
                  <label class="text-black" for="message">Address</label>
                  <textarea name="message" id="message" cols="30" rows="7" class="form-control" required></textarea>
                </div>
              </div>
                <div class="row form-group">

                <div class="col-md-12">
                  <label class="text-black" >District</label>
                  <select id="district" class="form-control" required>
                            <option >Thiruvanathapuram</option>
                            <option >Ernakulam</option>
                            <option >Malappuram</option>
                            <option >Kozhikode</option>
                            <option >Kannur</option>
                       </select>
                </div>
              </div>
                <div class="row form-group">

                <div class="col-md-12">
                  <label class="text-black" >Branch</label>
                   <select id="branch" class="form-control" required>
                            <option >Vattapara</option>
                            <option >Aruvikkara</option>
                            <option >karukapalli</option>
                            <option >edappalli</option>
                            <option >kondotty</option>
                             <option >kottakkal</option>
                        <option >mananchira</option>
                        <option >nadakkavu</option>
                        <option >payyannur</option>
                        <option >thaliparambu</option>
                       </select>
                </div>
                </div>
                    <div class="row form-group">

                <div class="col-md-12">
                  <label class="text-black" >Account type</label>
                   <select id="account" class="form-control" required>
                            <option >Savings account</option>
                            <option >current account</option>

                       </select>
                </div>
              </div>
                    <div class="row form-group">

                <div class="col-md-12">
                    <label class="text-black" >Materials provide</label><br>
                    <input type="checkbox" id="debitcard" name="debitcard" value="debit card">
                    <label for="debitcard"> debit card</label><br>
                    <input type="checkbox" id="creditcard" name="creditcard" value="credit card">
                    <label for="creditcard"> credit card</label><br>
                    <input type="checkbox" id="chequebook" name="chequebook" value="cheque book">
                    <label for="chequebook"> cheque book</label><br>
                </div>
                    </div>
              <div class="row form-group" align="center">
                <div class="col-md-6">
                    <button value="Submit" class="btn btn-primary btn-md text-white">Submit</button>
                </div>
                <div class="col-md-6">
                    <a class="btn btn-primary btn-md text-white" href="{% url 'credentials:logout' %}">logout</a>
<!--                        <input type="submit" value="Logout" class="btn btn-primary btn-md text-white"></a>-->
                </div>
                </div>

            </form>
          </div>

        </div>
      </div>
</section>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'js/jquery.sticky.js' %}"></script>
  <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>


  <script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
 {% if messages %}
        {% for message in messages %}
         {% if message.tags %}
            <script>alert("{{ message }}")

            </script>
        {% endif %}
        {% endfor %}
    {% endif %}
</body>
</html>

bankproject/bankproject/templates/home.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body style="background-image: url({% static 'images/hero_2.jpg' %});" data-aos="fade" id="home-section">
<form method="post" action="apply">
    {% csrf_token %}
    <div class="container" align="center" style="margin-top:200px;">
    <div class="col-lg-5 ml-auto" data-aos="fade-up" data-aos-delay="100">

            <h3 class="text-black mb-4" style="font-size:50px;">We Solve Your Financial Problem</h3>

            <p style="font-size:30px;margin-left:200px;margin-right:200px;" align="justify">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>

          </div>
<div align="center">
    <button type="submit" class="btn btn-outline-danger" style="border-radius: 40px;height:60px;font-size: 25px;background-color: #0C356A; box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);border: None;padding:15px;color:white;">APPLY NOW</button>
</div>
        </div>
</form>
</body>
</html>

bankproject/bankproject/templates/login.html
{% load static %}
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static 'images/bg-01.jpg' %});">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="post" action="login">
					{% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>



					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-90">New user?
						<a class="txt1" href="{% url 'credentials:register' %}">
							Register
						</a>
					</div>
				</form>
				{% for msg in messages %}
				<h3 style="color:red;">{{msg}}</h3>
				{% endfor %}
			</div>
		</div>
	</div>

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main1.js' %}"></script>

</body>
</html>

bankproject/bankproject/templates/register.html
{% load static %}
<html lang="en">
<head>
	<title>Registration</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static 'images/bg-01.jpg' %});">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="post" action="registrations">
    				{% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Register
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="user_name" placeholder="Username">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>
                    <div class="wrap-input100 validate-input" data-validate="Confirm password">
						<input class="input100" type="password" name="password1" placeholder="Confirm password">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Register
						</button>
					</div>

					<div class="text-center p-t-90">
						<a class="txt1" href="{% url 'credentials:login' %}">
							Login
						</a>
					</div>
				</form>
				{% for msg in messages %}
				<h3 style="color:red;">{{msg}}</h3>
				{% endfor %}
			</div>
		</div>
	</div>

	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main1.js' %}"></script>

</body>
</html>